### ISSUE TITLE
[Bug] Address Already In Use

### ISSUE THREAD

**Issue by RilDev** [kevinschoon/pomo#18]
Hi @kevinschoon,

Most of the time, when I try to `start` or `begin` a pomodoros, I get this error:
```
Error:
listen unix /home/cyril/.pomo/pomo.sock: bind: address already in use
```
I think it happens when I don't/[can't](https://github.com/kevinschoon/pomo/issues/15) leave the pomo timer with the proper `p` command.

The quick fix I found is to remove the `pomo.sock` file: `rm /home/cyril/.pomo/pomo.sock`

Cordially,
Cyril

**Comment by roxchgt** [comment]
I just encountered the bug and found out that when an ongoing Server is killed, for example closing the terminal without quitting the _pomo_ which in the code means not triggering the `*Server.Listener.close()`, the symlink `pomo.sock` in the config directory will stay there without being linked to any open socket (the address is been removed by os upon closing the term). Then attempting to start/begin a new pomo Server will fail because it supposes that there's an active pomo running and it's correct to not overwriting it… 

The consistent solution would be probably checking if any socket is open and listening associated with `&Config.SocketPath` when creating `NewServer(...)` in `server.go:41` and maybe interactively let user choose whether if s/he wants to overwrite or continue with the ongoing pomo…

unfortunately I know just the basics in Go and am not able to implement this yet!

**Comment by strogiyotec** [comment]
@roxchgt  @RilDev the last release has fixed this issue see https://github.com/kevinschoon/pomo/commit/adf5d8c4c9c506008eb4f6b78d272729b3ac76fe

**Comment by strogiyotec** [comment]
@kevinschoon Could you close this issue

**Comment by RilDev** [comment]
@strogiyotec Thanks for the fix!
