### ISSUE TITLE
What is the state of develop branch ?

### ISSUE THREAD

**Issue by strogiyotec** [kevinschoon/pomo#36]
@kevinschoon  Hey, I noticed that in some tickets you mentioned rewriting in dev branch , what is the state of this branch , which features were implemented, when are you going to merge it to master ?

**Comment by kevinschoon** [comment]
The develop branch is basically an abandoned experimental rewrite of Pomo with new features, it will build (but seems to have some bugs). I don't have any plans to merge it and will just keep it around for reference.

Background:

I had some free time last year and basically rewrote Pomo from scratch because I wasn't very happy with it's codebase. In the develop branch I started introducing some project management, note taking, and other concepts into the tool. I was also starting to think about the ability to distribute tasks between multiple users.. needless to say it is unfinished.

```
Usage: pomo [OPTIONS] COMMAND [arg...]

Pomodoro CLI

Options:
      --json      output as json
  -s, --socket    runtime socket path (default "/home/kevin/.local/share/pomo/pomo.sock")
      --db        path to a sqlite database (default "/home/kevin/.local/share/pomo/pomo.db")
  -v, --version   Show the version and exit

Commands:
  create, c       create a new task without starting
  config, cf      display the current configuration
  delete, d       delete a resource
  edit, e         edit a resource
  get, g          get one or more tasks
  init            initialize the sqlite database
  import          import existing task data
  history, h      browse and revert to previous states
  start, s        start a new task
  status, st      output the current status
```

Probably the most significant change is that tasks were grouped into a tree structure where branches could be used to organize projects and even share / export them with other users.
```
pomo get
[0] 0m root
├──[1] 0m/0m @ 0*50m hello world
│   └──[2] 0m/0m @ 0*50m fuu
│       └──[3] 0m/0m @ 0*50m bar
└──[4] 0m/0m @ 0*50m baz
```
I attached a rendering I came up with a while back here.
![pomo](https://user-images.githubusercontent.com/2986054/92745661-2c05e480-f348-11ea-9523-54a1b640c2f7.jpg)

**Comment by strogiyotec** [comment]
@kevinschoon  got it, but would you like to merge some parts that solve some github issues, lets' say this [issue](https://github.com/kevinschoon/pomo/issues/17) or we could reimplement them from scratch

**Comment by kevinschoon** [comment]
@strogiyotec probably best to reimplement from scratch, the change in the develop branch is too large.
