### ISSUE TITLE
Terminal alarm

### ISSUE THREAD

**Issue by Fubukimaru** [kevinschoon/pomo#5]
Would it be possible to implement the alarm for terminals?

Sometimes I don't see the notification in my secondary screen (I have it flipped for reading and other stuff) and I miss the notification. 

For me it would be quite useful to implement this as an option as it would produce a color change in my terminal and I would see it even if I'm not in the same workspace.

I'm not sure how this would be in Go, but in bash it's just printing an escape sequence:

```
sleep 3; echo -e "\a"
```

It also works in C++, so I assume it's a standard thing.

If you're busy or not wanting to implement this I could try to do it, but I would need a bit of support with Go :).

Thanks!

**Comment by kevinschoon** [comment]
@Fubukimaru we could definitely implement something for this though I wonder if it could be a more general solution. Pomo already implements a client/server interface that listens on a Unix socket, maybe we could add a configuration option that accepts a bash command which gets the `State` object piped to it as a json string on each change.

Feel free to create a PR for what I mention above or some other solution and I'm happy to review. 

Otherwise I can try to knock this out in a few weeks.

Thanks for the suggestion!

**Comment by Fubukimaru** [comment]
@kevinschoon Thanks for your reply!

It's not that you need to do this in bash. Actually the character '\a' is parsed by the terminal, so it should be doable in Go :).

If I'm able to, I'll try to hack it a bit. Thanks!

**Comment by strogiyotec** [comment]
@kevinschoon  @Fubukimaru  I also want to have an ability to notify me when pomo is over, however trick with bash won't work for ubuntu by default because Ubuntu no longer loads the hardware driver that produce beeps. I wonder if we could have an option to configure , something like a variable in config where you can choose between echo BEL and something else. I personally use `paplay` to play audio streams within terminal but I'm not sure if it's default executable for other linux distros

**Comment by strogiyotec** [comment]
@kevinschoon  what do you think about specifying path to bash script in config file that will be executed when pomo will be finished ?

**Comment by sboysel** [comment]
A more general solution to address executing arbitrary commands upon task state changes was implemented in #61.
